- name: Install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git-all
    - build-essential
    - libreadline-gplv2-dev
    - libssl-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - tklib
    - zlib1g-dev
    - openjdk-7-jre-headless
    - openjdk-7-jdk

- name: Install rbenv-load profile
  template: src=rbenv-load.sh
            dest=/etc/profile.d/rbenv-load.sh
            mode=0644

### rbenv

- name: Create rbenv target dir
  file: path={{rbenv_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- current_git_sha: git_dir={{rbenv_dir}}
  register: rbenv_current_git_sha

- name: Clone rbenv if not up to date
  sudo: True
  sudo_user: "{{user}}"
  git:  repo={{rbenv_repository}}
        dest={{rbenv_dir}}
        version={{rbenv_git_sha}}
  when: '"{{rbenv_current_git_sha.value}}" != "{{rbenv_git_sha}}"'



### ruby-build plugin

- name: Create target dir
  file: path={{rbenv_ruby_build_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- current_git_sha: git_dir={{rbenv_ruby_build_dir}}
  register: rbenv_ruby_build_current_git_sha

- name: Clone ruby-build plugin
  sudo: True
  sudo_user: "{{user}}"
  git:  repo={{rbenv_ruby_build_repository}}
        dest={{rbenv_ruby_build_dir}}
        version={{rbenv_ruby_build_sha}}
  when: '"{{rbenv_ruby_build_current_git_sha.value}}" != "{{rbenv_ruby_build_sha}}"'


### rbenv alias

- name: Create target dir
  file: path={{rbenv_ruby_aliases_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- current_git_sha: git_dir={{rbenv_ruby_aliases_dir}}
  register: rbenv_ruby_aliases_current_git_sha

- name: Clone rbenv alias plugin
  sudo: True
  sudo_user: "{{user}}"
  git: repo={{rbenv_ruby_aliases_repository}}
       dest={{rbenv_ruby_aliases_dir}}
       version={{rbenv_ruby_aliases_sha}}
  register: clone_rbenv_alias_plugin
  when: '"{{rbenv_ruby_aliases_current_git_sha.value}}" != "{{rbenv_ruby_aliases_sha}}"'

- name: Enable auto mode for rbenv alias
  command: su {{user}} -l -s /bin/bash -c "source /etc/profile.d/rbenv-load.sh && rbenv-load && rbenv alias --auto"
  when: clone_rbenv_alias_plugin.changed


### default gems

- name: Default gems config
  sudo: True
  sudo_user: "{{user}}"
  template: src=default-gems
            dest={{rbenv_dir}}/default-gems

- name: Create target dir for rbenv default-gem plugin
  file: path={{rbenv_default_gems_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- current_git_sha: git_dir={{rbenv_default_gems_dir}}
  register: rbenv_default_gems_current_git_sha

- name: Clone rbenv default-gems plugin
  sudo: True
  sudo_user: "{{user}}"
  git:  repo={{rbenv_default_gems_repository}}
        dest={{rbenv_default_gems_dir}}
        version={{rbenv_default_gems_sha}}
  when: '"{{rbenv_default_gems_current_git_sha.value}}" != "{{rbenv_default_gems_sha}}"'


### rehash

- name: Create target dir for rbenv gem-rehash plugin
  file: path={{rbenv_gem_rehash_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- current_git_sha: git_dir={{rbenv_gem_rehash_dir}}
  register: rbenv_gem_rehash_current_git_sha

- name: Clone rebenv gem-rehash plugin
  sudo: True
  sudo_user: "{{user}}"
  git:  repo={{rbenv_gem_rehash_repository}}
        dest={{rbenv_gem_rehash_dir}}
        version={{rbenv_gem_rehash_sha}}
  when: '"{{rbenv_gem_rehash_current_git_sha.value}}" != "{{rbenv_gem_rehash_sha}}"'


