- name: Install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - build-essential 
    - libreadline-gplv2-dev
    - libssl-dev
    - libxml2 
    - libxml2-dev 
    - libxslt1-dev
    - tklib 
    - zlib1g-dev 

- name: Install rbenv-load profile
  template: src=rbenv-load.sh
            dest=/etc/profile.d/rbenv-load.sh
            mode=0644

- name: Create target dir
  file: path={{rbenv_dir}}
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755


- name: Clone rbenv
  sudo: True
  sudo_user: "{{user}}"
  git:  repo=https://github.com/sstephenson/rbenv.git
        dest={{rbenv_dir}}
        version={{rbenv_git_sha}}


- name: Create target dir
  file: path=~{{user}}/.rbenv/plugins/ruby-build
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- name: Clone ruby-build plugin
  sudo: True
  sudo_user: "{{user}}"
  git:  repo=https://github.com/sstephenson/ruby-build.git 
        dest=~{{user}}/.rbenv/plugins/ruby-build
        version=d36e88c59effbab9b35403f58d34fcb1e0e4f45b


- name: Create target dir for rbenv alias plugin
  file: path=~{{user}}/.rbenv/plugins/rbenv-alias
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- name: Clone rbenv alias plugin
  sudo: True
  sudo_user: "{{user}}"
  git: repo=https://github.com/tpope/rbenv-aliases.git 
       dest=~{{user}}/.rbenv/plugins/rbenv-alias
       version=0505265e210feea1bc07980afe41229b657fb7f2
  register: clone_rbenv_alias_plugin

- name: Enable auto mode for rbenv alias 
  command: su {{user}} -l -s /bin/bash -c "source /etc/profile.d/rbenv-load.sh && rbenv-load && rbenv alias --auto"
  when: clone_rbenv_alias_plugin.changed

- name: Default gems config
  sudo: True
  sudo_user: "{{user}}"
  template: src=default-gems
            dest=~{{user}}/.rbenv/default-gems 

- name: Create target dir for rbenv default-gem plugin
  file: path=~{{user}}/.rbenv/plugins/rbenv-default-gems
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- name: Clone rbenv default-gems plugin 
  sudo: True
  sudo_user: "{{user}}"
  git:  repo=https://github.com/sstephenson/rbenv-default-gems.git
        dest=~{{user}}/.rbenv/plugins/rbenv-default-gems
        version=ead67889c91c53ad967f85f5a89d986fdb98f6fb


- name: Create target dir for rbenv gem-rehash plugin
  file: path=~{{user}}/.rbenv/plugins/rbenv-gem-rehash
        owner={{user}}
        group={{user}}
        state=directory
        mode=0755

- name: Rebenv gem-rehash plugin
  sudo: True
  sudo_user: "{{user}}"
  git:  repo=https://github.com/sstephenson/rbenv-gem-rehash.git
        dest=~{{user}}/.rbenv/plugins/rbenv-gem-rehash
        version=4d7b92de4bdf549df59c3c8feb1890116d2ea985

